[package]
name = "amend-editor"
version = "0.1.0"
edition = "2021"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[[bin]]
name = "amend-editor"
path = "src/main.rs"

[dependencies]
eframe = "0.26.2"
egui = "0.26.2"
egui_extras = "0.26.2"
rfd = "0.13"
winreg = "0.52" 